function [lab] = create_fancy_label(x, y, width, height, padding)
    lab.border = uicontrol(... % Border
         'Style', 'text',...
         'Position', [x y width height],...
         'BackgroundColor', [0 0 0]...
         );
    
	lab.padding = uicontrol(... % Padding
         'Style', 'text',...
         'Position', [
            x+1
            y+1
            width-2
            height-2
            ],...
         'BackgroundColor', [.9 .9 .9]...
         );
     
	lab.text = uicontrol(... % Label
         'Style', 'text',...
         'Position', [
            x+1+padding
            y+1+padding
            width-2-2*padding
            height-2-2*padding
            ],...
         'ForegroundColor', [0 0 0],...
         'BackgroundColor', [.9 .9 .9],...
         'HorizontalAlignment', 'center'...
         );
end
    