function status_update(text)
    global labStatus;
    
    set(labStatus.text,...
        'BackgroundColor', [0 1 0],...
        'String', text);
    set(labStatus.padding,...
        'BackgroundColor', [0 1 0]...
        );
    
    drawnow
    pause(0.1);
    
    set(labStatus.text,...
        'BackgroundColor', [.9 .9 .9]);
    set(labStatus.padding,...
        'BackgroundColor', [.9 .9 .9]...
        );
end